'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Ventrian.SimpleGallery
    
    Partial Public Class AddPhoto
        
        '''<summary>
        '''ucGalleryMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucGalleryMenu As Global.Ventrian.SimpleGallery.Controls.GalleryMenu
        
        '''<summary>
        '''imgStep control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgStep As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''lblStep control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStep As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblStepDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStepDescription As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblRequiresApproval control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRequiresApproval As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''pnlStep1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlStep1 As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''phStep1a control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phStep1a As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''rdoSelectExisting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoSelectExisting As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''plAlbum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAlbum As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''drpAlbums control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpAlbums As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''valSelectExisting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valSelectExisting As Global.System.Web.UI.WebControls.CustomValidator
        
        '''<summary>
        '''phStep1b control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phStep1b As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''rdoCreateNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoCreateNew As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''trParentAlbum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trParentAlbum As Global.System.Web.UI.HtmlControls.HtmlTableRow
        
        '''<summary>
        '''plParentAlbum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plParentAlbum As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''drpParentAlbum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpParentAlbum As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''plCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCaption As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCaption As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''valSelectNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valSelectNew As Global.System.Web.UI.WebControls.CustomValidator
        
        '''<summary>
        '''plDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDescription As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''pnlStep2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlStep2 As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litBatchID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litBatchID As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''fupFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fupFile As Global.System.Web.UI.WebControls.FileUpload
        
        '''<summary>
        '''btnUploadFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUploadFiles As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''addedPhotosRepeater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents addedPhotosRepeater As Global.System.Web.UI.WebControls.Repeater
        
        '''<summary>
        '''ucEditPhotos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucEditPhotos As Global.Ventrian.SimpleGallery.Controls.EditPhotos
        
        '''<summary>
        '''pnlWizard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlWizard As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''imgPrevious control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgPrevious As Global.System.Web.UI.WebControls.ImageButton
        
        '''<summary>
        '''cmdPrevious control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdPrevious As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''imgCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgCancel As Global.System.Web.UI.WebControls.ImageButton
        
        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''cmdNext control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdNext As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''imgNext control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgNext As Global.System.Web.UI.WebControls.ImageButton
        
        '''<summary>
        '''pnlSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSave As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''imgSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgSave As Global.System.Web.UI.WebControls.ImageButton
        
        '''<summary>
        '''cmdSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSave As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
