'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4963
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.SimpleGallery

    Partial Public Class EditSortOrder

        '''<summary>
        '''ucGalleryMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucGalleryMenu As Global.Ventrian.SimpleGallery.Controls.GalleryMenu

        '''<summary>
        '''dshAlbums control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshAlbums As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblEditSortOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblEditSortOrder As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plParentAlbum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plParentAlbum As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpParentAlbum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpParentAlbum As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plChildAlbums control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plChildAlbums As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblNoAlbums control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoAlbums As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlSortOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSortOrder As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lstAlbums control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstAlbums As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''lblAlbumUpdated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAlbumUpdated As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMovePage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMovePage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdUp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUp As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''hbtnUpHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hbtnUpHelp As Global.System.Web.UI.UserControl

        '''<summary>
        '''cmdDown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDown As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''hbtnDownHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hbtnDownHelp As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblActions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblActions As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdEdit As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''hbtnEditHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hbtnEditHelp As Global.System.Web.UI.UserControl

        '''<summary>
        '''cmdView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdView As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''hbtnViewHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hbtnViewHelp As Global.System.Web.UI.UserControl

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdReturnToGallery control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdReturnToGallery As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
