'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.SimpleGallery

    Partial Public Class EditAlbum

        '''<summary>
        '''ucGalleryMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucGalleryMenu As Global.Ventrian.SimpleGallery.Controls.GalleryMenu

        '''<summary>
        '''pnlSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSettings As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''dshAlbum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshAlbum As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblAlbumSettingsHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAlbumSettingsHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tblAlbum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblAlbum As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plParentAlbum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plParentAlbum As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpParentAlbum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpParentAlbum As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''valInvalidParentAlbum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valInvalidParentAlbum As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''plCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCaption As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCaption As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCaption As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDescription As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plInheritSecurity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plInheritSecurity As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkInheritSecurity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkInheritSecurity As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trPermissions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trPermissions As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plPermissions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPermissions As Global.System.Web.UI.UserControl

        '''<summary>
        '''grdAlbumPermissions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdAlbumPermissions As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''dshAdvanced control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshAdvanced As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblAdvanced control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblAdvanced As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plIsPublic control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plIsPublic As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkIsPublic control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsPublic As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHomeDirectory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHomeDirectory As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtHomeDirectory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHomeDirectory As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdCustomize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCustomize As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''valHomeDirectory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valHomeDirectory As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''trDefaultPhoto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trDefaultPhoto As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plDefaultPhoto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDefaultPhoto As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpDefaultPhoto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpDefaultPhoto As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plCreateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCreateDate As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpCreateTimeHour control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpCreateTimeHour As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''drpCreateTimeMinute control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpCreateTimeMinute As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtCreateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCreateDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdCreateCalendar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCreateCalendar As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''valtxtCreateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valtxtCreateDate As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDelete As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlDeleteTable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDeleteTable As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''dshDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshDelete As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblDeleteAlbum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblDeleteAlbum As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plDeletePhysicalFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDeletePhysicalFiles As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkDeletePhysicalFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDeletePhysicalFiles As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cmdDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlSynch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSynch As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlSynchronize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSynchronize As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''dshSynchronize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshSynchronize As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblSynchronize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblSynchronize As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plIncludeSubFolders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plIncludeSubFolders As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkIncludeSubFolders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIncludeSubFolders As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plAbsoluteSync control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAbsoluteSync As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkAbsoluteSync control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAbsoluteSync As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plResizeImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plResizeImages As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkResizeImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkResizeImages As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plAsynchronous control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAsynchronous As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkAsynchronous control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAsynchronous As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cmdSynchronize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSynchronize As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblSynchResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSynchResults As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
