'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.SimpleGallery

    Partial Public Class RandomPhotoOptions

        '''<summary>
        '''dshDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshDetails As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblBasic control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblBasic As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plModuleID As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpModuleID As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plAlbums control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAlbums As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpAlbums control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpAlbums As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMode As Global.System.Web.UI.UserControl

        '''<summary>
        '''rdoMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoMode As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plDisplay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDisplay As Global.System.Web.UI.UserControl

        '''<summary>
        '''rdoDisplay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoDisplay As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plMaxCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMaxCount As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtMaxCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaxCount As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valMaxCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valMaxCount As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valMaxCountIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valMaxCountIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plTagFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTagFilter As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTagFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTagFilter As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plRepeatDirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRepeatDirection As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpRepeatDirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpRepeatDirection As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plRepeatColumns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRepeatColumns As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtRepeatColumns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRepeatColumns As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valRepeatColumns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valRepeatColumns As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valRepeatColumnsIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valRepeatColumnsIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plBorderStyle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plBorderStyle As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpBorderStyle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpBorderStyle As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''dshAdvanced control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshAdvanced As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblAdvanced control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblAdvanced As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plLaunchSlideshow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLaunchSlideshow As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkLaunchSlideshow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkLaunchSlideshow As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plAlbumSlideshow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAlbumSlideshow As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkAlbumSlideshow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAlbumSlideshow As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plIncludeJQuery control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plIncludeJQuery As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkIncludeJQuery control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIncludeJQuery As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''dshCompressionSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshCompressionSettings As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblCompressionSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblCompressionSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plCompressionType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCompressionType As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpCompressionType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpCompressionType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plThumbnailType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plThumbnailType As Global.System.Web.UI.UserControl

        '''<summary>
        '''rdoThumbnailType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoThumbnailType As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''trWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trWidth As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plWidth As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valWidth As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valWidthIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valWidthIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''trHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trHeight As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHeight As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valHeight As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valHeightIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valHeightIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''trSquare control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trSquare As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plSquare control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSquare As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSquare control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSquare As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valSquare control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valSquare As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valSquareIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valSquareIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''dshTemplateSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshTemplateSettings As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblTemplateSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblTemplateSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plTemplateType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTemplateType As Global.System.Web.UI.UserControl

        '''<summary>
        '''rdoTemplateType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoTemplateType As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''trPhotoTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trPhotoTemplate As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plPhotoTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPhotoTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtPhotoTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPhotoTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trAlbumTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trAlbumTemplate As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plAlbumTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAlbumTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtAlbumTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAlbumTemplate As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
