'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1434
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.SimpleGallery

    Partial Public Class SearchOptions

        '''<summary>
        '''plModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plModuleID As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpModuleID As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''dshTemplateSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshTemplateSettings As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblTemplateSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblTemplateSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plSearchTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSearchTemplate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtSearchTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSearchTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblButton As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLinkButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLinkButton As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTextBox As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
