'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.SimpleGallery

    Partial Public Class ViewOptions

        '''<summary>
        '''dshDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshDetails As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblBasic control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblBasic As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plAlbumFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAlbumFilter As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpAlbumFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpAlbumFilter As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plAlbumsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAlbumsPerRow As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtAlbumsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAlbumsPerRow As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valAlbumsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valAlbumsPerRow As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valAlbumsPerRowIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valAlbumsPerRowIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plAlbumSortBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAlbumSortBy As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpAlbumSortBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpAlbumSortBy As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plAlbumSortDirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAlbumSortDirection As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpAlbumSortDirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpAlbumSortDirection As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plBorderStyle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plBorderStyle As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpBorderStyle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpBorderStyle As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plThumbnailsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plThumbnailsPerRow As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtThumbnailsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtThumbnailsPerRow As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valThumbnailsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valThumbnailsPerRow As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valThumbnailsPerRowIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valThumbnailsPerRowIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plPhotosPerPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPhotosPerPage As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtPhotosPerPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPhotosPerPage As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valPhotosPerPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPhotosPerPage As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valPhotoPageSizeIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPhotoPageSizeIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plSortBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSortBy As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpSortBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpSortBy As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plSortDirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSortDirection As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpSortDirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpSortDirection As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''dshAdvanced control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshAdvanced As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblAdvanced control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblAdvanced As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plAlbumDefaultPath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAlbumDefaultPath As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtAlbumDefaultPath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAlbumDefaultPath As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plLightboxDefaultPath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLightboxDefaultPath As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtLightboxDefaultPath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLightboxDefaultPath As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plEnableSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableSearch As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnableSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableSearch As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plEnableSyndication control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableSyndication As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnableSyndication control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableSyndication As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plEnableTooltip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableTooltip As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnableTooltip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableTooltip As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHideBreadCrumbs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideBreadCrumbs As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHideBreadCrumbs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideBreadCrumbs As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHidePager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHidePager As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHidePager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHidePager As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plIncludeJQuery control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plIncludeJQuery As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkIncludeJQuery control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIncludeJQuery As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plIncludeViewCart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plIncludeViewCart As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkIncludeViewCart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIncludeViewCart As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plUseAlbumAnchors control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUseAlbumAnchors As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkUseAlbumAnchors control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUseAlbumAnchors As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''dshCompression control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshCompression As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblCompression control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblCompression As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblResizeInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblResizeInstructions As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plResizePhoto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plResizePhoto As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkResizePhoto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkResizePhoto As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plCompressionType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCompressionType As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpCompressionType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpCompressionType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plImageWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plImageWidth As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtImageWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtImageWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valImageWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valImageWidth As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valImageWidthIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valImageWidthIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plImageHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plImageHeight As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtImageHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtImageHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valImageHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valImageHeight As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valImageHeightIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valImageHeightIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plUseWatermark control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUseWatermark As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkUseWatermark control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUseWatermark As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plWatermarkText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plWatermarkText As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtWatermarkText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWatermarkText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plWatermarkImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plWatermarkImage As Global.System.Web.UI.UserControl

        '''<summary>
        '''ctlWatermarkImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlWatermarkImage As DotNetNuke.UI.UserControls.UrlControl

        '''<summary>
        '''plWatermarkPosition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plWatermarkPosition As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpWatermarkPosition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpWatermarkPosition As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblResizeAlbumInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblResizeAlbumInstructions As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plCompressionTypeAlbum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCompressionTypeAlbum As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpCompressionTypeAlbum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpCompressionTypeAlbum As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plThumbnailTypeAlbum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plThumbnailTypeAlbum As Global.System.Web.UI.UserControl

        '''<summary>
        '''rdoThumbnailTypeAlbum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoThumbnailTypeAlbum As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''trAlbumThumbnailWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trAlbumThumbnailWidth As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plAlbumThumbnailWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAlbumThumbnailWidth As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtAlbumThumbnailWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAlbumThumbnailWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valAlbumThumbnailWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valAlbumThumbnailWidth As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valAlbumThumbnailWidthIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valAlbumThumbnailWidthIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''trAlbumThumbnailHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trAlbumThumbnailHeight As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plAlbumThumbnailHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAlbumThumbnailHeight As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtAlbumThumbnailHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAlbumThumbnailHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valAlbumThumbnailHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valAlbumThumbnailHeight As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valAlbumThumbnailHeightIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valAlbumThumbnailHeightIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''trAlbumThumbnailSquare control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trAlbumThumbnailSquare As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plAlbumThumbnailSquare control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAlbumThumbnailSquare As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtAlbumThumbnailSquare control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAlbumThumbnailSquare As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valAlbumThumbnailSquare control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valAlbumThumbnailSquare As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valAlbumThumbnailSquareIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valAlbumThumbnailSquareIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''lblResizePhotoInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblResizePhotoInstructions As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plCompressionTypePhoto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCompressionTypePhoto As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpCompressionTypePhoto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpCompressionTypePhoto As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plThumbnailTypePhoto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plThumbnailTypePhoto As Global.System.Web.UI.UserControl

        '''<summary>
        '''rdoThumbnailTypePhoto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoThumbnailTypePhoto As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''trThumbnailWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trThumbnailWidth As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plThumbnailWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plThumbnailWidth As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtThumbnailWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtThumbnailWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valThumbnailWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valThumbnailWidth As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valThumbnailWidthIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valThumbnailWidthIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''trThumbnailHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trThumbnailHeight As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plThumbnailHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plThumbnailHeight As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtThumbnailHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtThumbnailHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valThumbnailHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valThumbnailHeight As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Comparevalidator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Comparevalidator1 As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''trThumbnailSquare control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trThumbnailSquare As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plThumbnailSquare control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plThumbnailSquare As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtThumbnailSquare control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtThumbnailSquare As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valThumbnailSquare control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valThumbnailSquare As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valThumbnailSquareIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valThumbnailSquareIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''dshSecurity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshSecurity As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblSecurity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblSecurity As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plPhotoModeration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPhotoModeration As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkPhotoModeration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkPhotoModeration As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plPhotoPermissions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPhotoPermissions As Global.System.Web.UI.UserControl

        '''<summary>
        '''dgPhotoPermissions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgPhotoPermissions As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''dshSlideShow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshSlideShow As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblSlideShow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblSlideShow As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plSlideshowType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSlideshowType As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpSlideshowType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpSlideshowType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''trStandardWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trStandardWidth As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtStandardWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStandardWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valStandardWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valStandardWidth As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valStandardWidthIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valStandardWidthIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''trPopupWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trPopupWidth As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plPopupWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPopupWidth As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtPopupWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPopupWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valPopupWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPopupWidth As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valPopupWidthIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPopupWidthIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''trPopupHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trPopupHeight As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plPopupHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPopupHeight As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtPopupHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPopupHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valPopupHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPopupHeight As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valPopupHeightIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPopupHeightIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''trEnableScrollbar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trEnableScrollbar As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plEnableScrollbar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableScrollbar As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnableScrollbar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableScrollbar As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trLightboxNextKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trLightboxNextKey As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plNextKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plNextKey As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtNextKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNextKey As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valNextKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valNextKey As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''trLightboxPreviousKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trLightboxPreviousKey As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plPreviousKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPreviousKey As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtPreviousKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPreviousKey As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valPreviousKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPreviousKey As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''trLightboxCloseKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trLightboxCloseKey As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plCloseKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCloseKey As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtCloseKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCloseKey As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valCloseKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCloseKey As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''trLightboxDownloadKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trLightboxDownloadKey As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plDownloadKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDownloadKey As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtDownloadKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDownloadKey As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valDownloadKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valDownloadKey As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''trLightboxSlideInterval control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trLightboxSlideInterval As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plSlideInterval control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSlideInterval As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSlideInterval control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSlideInterval As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valSlideInterval control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valSlideInterval As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valSlideIntervalIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valSlideIntervalIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''trLightboxHideTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trLightboxHideTitle As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plSlideHideTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSlideHideTitle As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkSlideHideTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSlideHideTitle As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trLightboxHideDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trLightboxHideDescription As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plSlideHideDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSlideHideDescription As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkSlideHideDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSlideHideDescription As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trLightboxHidePaging control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trLightboxHidePaging As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plSlideHidePaging control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSlideHidePaging As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkSlideHidePaging control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSlideHidePaging As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trLightboxHideTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trLightboxHideTags As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plSlideHideTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSlideHideTags As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkSlideHideTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSlideHideTags As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trLightboxHideDownload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trLightboxHideDownload As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plSlideHideDownload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSlideHideDownload As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkSlideHideDownload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSlideHideDownload As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''dshTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshTags As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblTags As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTags As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnableTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableTags As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plRequireTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRequireTags As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkRequireTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkRequireTags As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plTagCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTagCount As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTagCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTagCount As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valTagCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valTagCount As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valTagCountIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valTagCountIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''dshUploader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshUploader As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblUploader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblUploader As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plUploaderFileSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUploaderFileSize As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtUploaderFileSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUploaderFileSize As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valUploaderFileSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valUploaderFileSize As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valUploaderFileSizeIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valUploaderFileSizeIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plUseXmpExif control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUseXmpExif As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkUseXmpExif control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUseXmpExif As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''dshZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshZip As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblZip As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plEnableZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableZip As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnableZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableZip As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plIncludeSubFolders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plIncludeSubFolders As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkIncludeSubFolders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIncludeSubFolders As Global.System.Web.UI.WebControls.CheckBox
    End Class
End Namespace
