'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.SimpleGallery.Controls

    Partial Public Class EditPhotos

        '''<summary>
        '''litCommandsAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCommandsAdd As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litCommandsDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCommandsDelete As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''phBatchOperations control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phBatchOperations As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''plBatchOperations control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plBatchOperations As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTagsAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTagsAdd As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblTagsAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTagsAdd As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTagsClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTagsClear As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dlGallery control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dlGallery As Global.System.Web.UI.WebControls.DataList
    End Class
End Namespace
