'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4963
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.SimpleGallery.Controls

    Partial Public Class GalleryMenu

        '''<summary>
        '''rptBreadCrumbs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptBreadCrumbs As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''phSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phSearch As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''lnkSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkSearch As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lnkTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkTags As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lnkRSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkRSS As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''imgRSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgRSS As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''trSeparator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trSeparator As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''pnlCommandBar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCommandBar As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lnkAddNewPhoto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkAddNewPhoto As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lnkAddNewAlbum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkAddNewAlbum As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lnkApprovePhotos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkApprovePhotos As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lnkBulkEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkBulkEdit As Global.System.Web.UI.WebControls.HyperLink
    End Class
End Namespace
