'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.SimpleGallery.Controls

    Partial Public Class ViewPhotos

        '''<summary>
        '''phPopupScripts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phPopupScripts As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''phjQueryScripts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phjQueryScripts As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''phLightboxScripts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phLightboxScripts As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''phLightboxTop control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phLightboxTop As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''dlGallery control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dlGallery As Global.System.Web.UI.WebControls.DataList

        '''<summary>
        '''pnlPaging control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPaging As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lnkPrev control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkPrev As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblCurrentPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrentPage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lnkNext control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkNext As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''phLightboxBottom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phLightboxBottom As Global.System.Web.UI.WebControls.PlaceHolder
    End Class
End Namespace
